version: '3.7'

services:
  currency-exchange:
    image: bentagtow/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      naming-server:
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://localhost:8761/eureka


  naming-server:
    image: bentagtow/mmv2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network: